#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vvveb"
name = "Vvveb"
description.en = "CMS to build websites, blogs or ecommerce stores"
description.fr = "CMS pour créer des sites Web, des blogs ou des boutiques de commerce électronique"

version = "1.0.7~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://www.vvveb.com/"
admindoc = "https://docs.vvveb.com/installation"
code = "https://github.com/givanz/Vvveb"
fund = "https://www.vvveb.com/page/sponsor"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/vvveb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/givanz/Vvveb/archive/refs/tags/1.0.7.tar.gz"
    sha256 = "496941690244e9492f73699cf8c43c3ad7416aa16e68f9db0084645736c78f78"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, php8.4-pgsql, php8.4-xml, php8.4-zip, php8.4-dom, php8.4-curl, php8.4-gettext, php8.4-gd"

    [resources.database]
type = "postgresql"
