#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    [default.curl_tests]
        # TODO: is theme missing in default install?
        home.auto_test_assets = false

